{{config(materialized='table')}}



WITH IMPUTEDDATA AS (
    SELECT
        CUSTOMER,
        COALESCE(OVERALLSATISFACTION, (SELECT MEDIAN(OVERALLSATISFACTION) FROM INITIALSURVEYDATA)) AS OVERALLSATISFACTION,
        COALESCE(FOODQUALITY, (SELECT MEDIAN(FOODQUALITY) FROM INITIALSURVEYDATA)) AS FOODQUALITY,
        COALESCE(SPEEDSATISFACTION, (SELECT MEDIAN(SPEEDSATISFACTION) FROM INITIALSURVEYDATA)) AS SPEEDSATISFACTION,
        COALESCE(ORDERACCURACY, 'Yes') AS ORDERACCURACY
    FROM INITIALSURVEYDATA
)

SELECT * FROM IMPUTEDDATA
